# Generated by Django 5.1.6 on 2025-03-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='file_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
