# Generated by Django 5.1.6 on 2025-03-07 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0002_filemetadata_file_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField(help_text='Sequence number of this chunk')),
                ('chunk_size', models.PositiveBigIntegerField(help_text='Size of this chunk in bytes')),
                ('checksum', models.CharField(help_text='Checksum (e.g. MD5 or SHA256) to verify integrity', max_length=64)),
                ('storage_node', models.CharField(help_text='Name of the MinIO server node e.g., minio-node1', max_length=50)),
                ('object_key', models.CharField(help_text='Object key in MinIO where the chunk is stored', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='storage_app.filemetadata')),
            ],
        ),
    ]
