# Generated by Django 5.1.6 on 2025-03-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0003_filechunk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filechunk',
            options={'ordering': ['chunk_index'], 'verbose_name': 'File Chunk', 'verbose_name_plural': 'File Chunks'},
        ),
        migrations.AlterModelOptions(
            name='filemetadata',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'File Metadata', 'verbose_name_plural': 'File Metadata'},
        ),
        migrations.AddField(
            model_name='filechunk',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Indicates if the chunk's checksum has been verified"),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='is_chunked',
            field=models.BooleanField(default=False, help_text='Indicates if the file has been split into chunks'),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='original_checksum',
            field=models.CharField(help_text='Checksum of the complete original file', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='total_chunks',
            field=models.PositiveIntegerField(default=1, help_text='Total number of chunks for this file'),
        ),
        migrations.AlterUniqueTogether(
            name='filechunk',
            unique_together={('file', 'chunk_index')},
        ),
    ]
