# Generated by Django 5.1.6 on 2025-03-11 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0005_alter_filemetadata_original_checksum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('used_space', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('file_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_app.filemetadata')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_app.node')),
            ],
        ),
    ]
